# -*- coding: utf-8 -*-
"""SaliencyMaps.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bbtpaRDSIeL9Xnnzraw2u_--tAZ29mJ3
"""
# flashtorch and torch need to be installed
from flashtorch.saliency import Backprop
from flashtorch.utils import load_image, apply_transforms, denormalize, format_for_plotting

PATH = 'FILLER PATH'
input = apply_transforms(load_image(PATH))
# COVID-19 is 0, Normal is 1, Viral Pneumonia is 2
target_class = 0

MODEL = 'FILLER PATH'
model = torch.load(MODEL)

# Backprop object is used to calculate the gradients of the NN
backprop = Backprop(model)

# regular visualization
gradients = backprop.calculate_gradients(input, target_class)
max_gradients = backprop.calculate_gradients(input, target_class, take_max=True)
backprop.visualize(input, target_class)

# less noisy guided visualization
guided_gradients = backprop.calculate_gradients(input, target_class, guided=True)
max_guided_gradients = backprop.calculate_gradients(input, target_class, take_max=True, guided=True)
# visualize
backprop.visualize(input, target_class)
